### ISSUE TITLE
✨ Zendesk Chat 

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/zzSSW.Website#11]
Cc: @adamcogan @pierssinclairssw @christianmorfordwaitessw 

To Myself
  
### Tasks

- [x] Investigate how the "Chat with us" feature on the SSW Website is done
- [x] Add the feature to the new website

Thanks!

**Comment by ozair-ashfaque** [comment]
All done - see
![image](https://user-images.githubusercontent.com/96504411/153088704-91686085-8835-4db1-b89b-e5cdc687df7a.png)
**Figure: Zendesk answer bot added to the website**

Test messages were sent using Zendesk:
![image](https://user-images.githubusercontent.com/96504411/153089640-d1881ce3-9a93-4af4-b26a-874841c19c9a.png)
**Figure: Messages were received by human agent**
