### ISSUE TITLE
👷 DevOps - Rename workflows

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/zzSSW.Website#116]
Cc: @ozairashfaqueSSW  @pierssinclairssw @adamcogan 

To Myself,
  
### Pain

Some current workflow names are ambiguous.

### Tasks

- [x] Rename `Build` workflow to `PR - Build`
- [x] Rename `Build and Deploy Gatsby` workflow to `Reuseable - Build and Deploy Gatsby`

### Screenshots

![image](https://user-images.githubusercontent.com/37203901/154879549-26e2655f-f34c-4661-9ec3-a972a7b2b18e.png)
Figure: Current workflows

Thanks!

**Comment by ozair-ashfaque** [comment]
Done - see
![image](https://user-images.githubusercontent.com/96504411/155250835-9dd1c30d-247b-4351-9b3f-88cf44cb7451.png)
**Figure: Workflows have been renamed to remove ambiguity**
