### ISSUE TITLE
👷 DevOps - Add CodeAuditor

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/zzSSW.Website#117]
Cc: @ozairashfaqueSSW @pierssinclairssw @adamcogan 

To myself,
  
### Pain

We need to have a CodeAuditor check after deploying to the staging environment.

### Tasks

- [x] Add CodeAudior after staging build

Thanks!

**Comment by ozair-ashfaque** [comment]
Done - see
![image](https://user-images.githubusercontent.com/96504411/155250545-3e5e5613-872d-4aab-b62d-9b1bd7fb0366.png)
**Figure: CodeAuditor test runs to check the broken links, after the deployment to staging**
