### ISSUE TITLE
✨Consulting - Migrate 'Are You Stuck?'

### ISSUE THREAD

**Issue by lukecookssw** [SSWConsulting/zzSSW.Website#149]
Cc: @pierssinclairssw 

Hi @kevinpho2022 
  
### Pain

The page [Are you stuck?](https://www.ssw.com.au/ssw/Consulting/Are-You-Stuck.aspx) does not fit our existing content template flow.

### Suggested Solution

This page is fairly unique, so we won't use the template but instead build it out as a straight React/Gatsby page with no MDX requirement. Write the 'are-you-stuck' page as a pure React/Gatsby page, reusing existing components where you can.

### Tasks

- [x] Identify reusable components (customer quotes, companies we've worked with, etc.) that are already built
- [x] #162
- [x] #163
- [x] #173
- [x] #174
- [x] #196

 

Thanks!

**Comment by kevinpho2022** [comment]
Done - Thanks to everyone that helped me! It was great working with everyone.
