### ISSUE TITLE
✨Consulting - Images rendering using MDX

### ISSUE THREAD

**Issue by ozair-ashfaque** [SSWConsulting/zzSSW.Website#152]
Cc: @adamcogan @pierssinclairssw @lukecookssw @AttackOnMorty @paulsmythssw @bigtony97 @kevinpho2022 

To Myself, 
  
### Pain

Currently, images are not supported in the markdown. They are not rendered from [content repo](https://github.com/SSWConsulting/SSW.Website.Content)
### Suggested Solution

Gatsby plugin like **"gatsby-remark-images"** needs to be configured for [MDX plugin](https://www.gatsbyjs.com/docs/working-with-images-in-markdown/). 
### Tasks

- [x] Investigate how to render image using mdx plugin
- [x] Deploy the relevant plugin to start rendering images.

### More Information

Twp plugins are available gatsby-remark-images and gatsby-transformer-remark for rendering images on [markdown](https://www.gatsbyjs.com/docs/working-with-images-in-markdown/)
### Screenshots

![image](https://user-images.githubusercontent.com/96504411/164591904-67fa9eb2-7709-4013-be3e-8d10542f097d.png)
**Figure: Images in not rendered from the mdx file of contet repo**
Thanks!

**Comment by doueal** [comment]
Added gatsby-remark-images which renders inline images - https://github.com/SSWConsulting/SSW.Website/pull/200

![image](https://user-images.githubusercontent.com/71110132/171760196-704555b7-1bd5-4712-a37d-8844804f9ae0.png)
Figure: Remote work image on the consulting/remote-work page
