### ISSUE TITLE
✨Update text and images on consulting/consulting page

### ISSUE THREAD

**Issue by lukecookssw** [SSWConsulting/zzSSW.Website#177]
Cc: @adamcogan @pierssinclairssw @lukecookssw 

To Myself
  
### Pain

The page content on the [consulting options](https://frontdoorstaging.z01.azurefd.net/consulting-options/) page is out of date.

### Suggested Solution

Write updated content and replace it.

### Tasks

- [x] Ask the PO for input in which content to update and how it should be written
- [x] Write content
- [x] Replace content

Thanks!

**Comment by doueal** [comment]
Done - https://github.com/SSWConsulting/SSW.Website/pull/182
