### ISSUE TITLE
✨Create consulting pages based on file directory

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/zzSSW.Website#22]
Cc: @adamcogan @pierssinclairssw @christianmorfordwaitessw @AttackOnMorty 

To Myself
  
### Pain

Currently in Rules, we define a rule's URL based on the front matter. This isn't great because we need to change the folder name and frontmatter when updating the uri of a rule.

### Suggested Solution

Use GraphQL magic to define pages by their folder names.

### Tasks

- [x] Investigate
- [x] Create /consulting pages based on folder names in the content repo

Thanks!

**Comment by Hona** [comment]
How would this GraphQL solution work?

Since we are generating this site statically could we not just generate it from the filesystem paths?

**Comment by tkapa** [comment]
The intention is to use GraphQL File nodes to get the route and use the createPage function in the gatsby-node to define it.

That's how I've set it up currently and it works. Though I can see it potentially bloating the solution if we need to customise all types of pages we have. 

If you're able to help me find a way to do this based on where the files from the github source go when they're pulled in. I'm happy to investigate that option instead.
