### ISSUE TITLE
✨ Index page - Add core services panels

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/zzSSW.Website#34]
Cc: @adamcogan @AttackOnMorty @pierssinclairssw @christianmorfordwaitessw 

To Myself 
  
### Pain
The new index page isn't quite like the existing production SSW Website index page

### Tasks

- [x] Add Core Services panels

### Screenshots
![image](https://user-images.githubusercontent.com/17246482/147036219-094679fb-a494-498d-b9d6-2e681d0c884e.png)
**Figure: Core Services panel**

Thanks!

**Comment by piers-sinclair** [comment]
@ozairashfaqueSSW @AttackOnMorty should this be closed already?

**Comment by AttackOnMorty** [comment]
> @ozairashfaqueSSW @AttackOnMorty should this be closed already?

Yes, it's already been done.
