### ISSUE TITLE
✨ Index Page - Enhance Carousel component

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/zzSSW.Website#41]
Cc: @pierssinclairssw @adamcogan 

Hi @ozairashfaqueSSW 
  
### Pain

As per our conversation in the Sprint Review 5, we need to add a few enhancements to the Carousel component

### Tasks

- [x] Add pop-up for `why choose SSW` Vimeo video
- [x] Make carousel indicators larger while hovering

### Screenshots

![image](https://user-images.githubusercontent.com/37203901/151279859-94729bdc-cc2b-4189-bb52-f6311e895fd3.png)
**Figure: Clickable `why choose SSW` image and carousel indicators**

Thanks!

**Comment by ozair-ashfaque** [comment]
All done -see
![image](https://user-images.githubusercontent.com/96504411/152084852-e9a1a330-944f-47cd-b449-dbabb902a05c.png)
**Figure: Carousel indicators larger while hovering**
![image](https://user-images.githubusercontent.com/96504411/152084952-8405f2e2-e780-444e-9bb7-f97a8c9b0549.png)
**Figure: Vimeo Pop-up video added**

**Comment by ozair-ashfaque** [comment]
As per discussion with @adamcogan, reduce the carousel indicator size:
![2022-02-02_17-09-52](https://user-images.githubusercontent.com/96504411/152102505-a9e838c0-5d94-4a16-a54a-2fb8af42218c.gif)
