### ISSUE TITLE
✨ Consulting Template - Add booking form

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/zzSSW.Website#47]
Cc: @adamcogan @pierssinclairssw @lukecookssw @AttackOnMorty 

To Myself,
  
### Pain

We would like to add consulting booking form

### Tasks

- [x] Investigate the old booking form
- [x] Add new booking form to [Template - Consulting page](https://github.com/SSWConsulting/SSW.Website/issues/6)

### Screenshots

![image](https://user-images.githubusercontent.com/96504411/161361984-2f3bd0e5-fbd9-4aea-b99b-e84177e7380f.png)
**Figure: Consulting booking form for SSW website**

Thanks!

**Comment by ozair-ashfaque** [comment]
> - [x] Add new booking form to [Template - Consulting page](https://github.com/SSWConsulting/SSW.Website/issues/6)

Done - see
![image](https://user-images.githubusercontent.com/96504411/161863179-be431931-b73c-435c-8c4b-9c26f6d9db9c.png)
**Figure: Bookingform template is added in Consulting Page template**

**Comment by ozair-ashfaque** [comment]
> - [ ] Add axios post method for endpoint of Azure Function

Blocker - Axios post method cannot be implemented until [Azure Functions](#138 ) are created.
Deleted - moved to separate issue
