### ISSUE TITLE
👷 DevOps - Build health check update

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/zzSSW.Website#54]
Cc: @adamcogan @pierssinclairssw @AttackOnMorty 

To Myself
  
### Pain
Currently the `build-main.yml` workflow has hardcoded values for the environment variables

### Tasks

- [x] Update this workflow to use `Staging` as an environment
- [ ] Optionally: Add another step that runs with the `Production` environment

Thanks!

**Comment by tkapa** [comment]
PR created and linked.

    > Optionally: Add another step that runs with the `Production` environment
Personally, I don't think that this will help, so I have not implemented it in the PR.

**Comment by AttackOnMorty** [comment]
> PR created and linked.
> 
> ```
> > Optionally: Add another step that runs with the `Production` environment
> ```
> 
> Personally, I don't think that this will help, so I have not implemented it in the PR.

Yes, we don't need that. Actually, content repo should only have a `main` branch (`staging` branch is not needed)
