### ISSUE TITLE
♻️  Index page - Extract consulting and services panels to components

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/zzSSW.Website#83]
Cc: @pierssinclairssw @adamcogan 

Hi @ozairashfaqueSSW 

### Pain

In the index page, consulting and services panels should be extracted to components and using CSS module.

### Tasks

- [x] Extract consulting and services components
- [x] Using CSS module instead of CSS

### Screenshots

![image](https://user-images.githubusercontent.com/37203901/150051278-d22389a2-e6b2-4939-b316-1be9a4eaca60.png)
**Figure: Index page**

Thanks!

**Comment by ozair-ashfaque** [comment]
All done - see
![image](https://user-images.githubusercontent.com/96504411/154190858-7f289a07-be91-4088-b11d-15deb429def1.png)
**Figure: Consulting and core services have their individual components**
