### ISSUE TITLE
✨  Add Google Analytics

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/zzSSW.Website#85]
Cc: @ozairashfaqueSSW @pierssinclairssw @adamcogan 

To myself,

### Tasks

- [x] Add Google Analytics

Thanks!

**Comment by ozair-ashfaque** [comment]
Done - see
![image](https://user-images.githubusercontent.com/96504411/152085217-25af0c7e-2c37-4800-846d-f74e90946dc4.png)
**Figure: Google Analytics GA4 Configuration is added to https://staging2.ssw.com.au/ssw/ container**
